use crate::models::result::{ScanFinding, ScanSummary};
use std::fs::File;
use std::io::{self, Write};
use std::path::Path;

pub struct MarkdownReporter;

impl MarkdownReporter {
    /// Generate and write a formatted Markdown vulnerability report.
    pub fn write_report(
        findings: &[ScanFinding],
        summary: Option<&ScanSummary>,
        output_path: &str,
    ) -> io::Result<()> {
        let path = Path::new(output_path);
        let mut file = File::create(path)?;

        writeln!(file, "# Nuclei Scan Vulnerability Report\n")?;
        writeln!(file, "Generated by `nuclei-run` at {}\n", chrono::Utc::now().to_rfc3339())?;

        if let Some(sum) = summary {
            writeln!(file, "## Scan Summary\n")?;
            writeln!(file, "| Metric | Value |")?;
            writeln!(file, "| :--- | :--- |")?;
            writeln!(file, "| **Total Requests** | {} |", sum.total_requests)?;
            writeln!(file, "| **Total Findings** | {} |", sum.total_findings)?;
            writeln!(file, "| **Templates Loaded** | {} |", sum.templates_loaded)?;
            writeln!(file, "| **Targets Scanned** | {} |", sum.targets_scanned)?;
            writeln!(file, "| **Duration** | {:.2}s |", sum.elapsed_millis as f64 / 1000.0)?;
            writeln!(file, "| **Scan Speed** | {:.1} req/sec |\n", sum.rps)?;
        }

        writeln!(file, "## Findings Matrix\n")?;
        if findings.is_empty() {
            writeln!(file, "*No vulnerabilities or findings detected.*\n")?;
        } else {
            writeln!(file, "| Severity | Template ID | Name | Protocol | Matched Target | Extracted Data |")?;
            writeln!(file, "| :--- | :--- | :--- | :--- | :--- | :--- |")?;

            for finding in findings {
                let extracted = if finding.extracted_results.is_empty() {
                    "-".to_string()
                } else {
                    format!("`{}`", finding.extracted_results.join(", "))
                };

                let sev_badge = match finding.severity.to_lowercase().as_str() {
                    "critical" => "**🔴 CRITICAL**",
                    "high" => "**🟠 HIGH**",
                    "medium" => "**🟡 MEDIUM**",
                    "low" => "**🔵 LOW**",
                    _ => "⚪ INFO",
                };

                writeln!(
                    file,
                    "| {} | `{}` | {} | `{}` | `{}` | {} |",
                    sev_badge,
                    finding.template_id,
                    finding.template_name,
                    finding.protocol,
                    finding.matched_url,
                    extracted
                )?;
            }
        }

        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_markdown_report_generation() {
        let findings = vec![ScanFinding {
            template_id: "test-cve".to_string(),
            template_name: "Test CVE".to_string(),
            severity: "high".to_string(),
            matched_url: "https://example.com/vuln".to_string(),
            matched_at: "2026-08-27T00:00:00Z".to_string(),
            extracted_results: vec!["admin".to_string()],
            protocol: "http".to_string(),
            matcher_name: None,
            tags: None,
        }];

        let temp_file = tempfile::NamedTempFile::new().unwrap();
        let path = temp_file.path().to_str().unwrap();

        MarkdownReporter::write_report(&findings, None, path).unwrap();
        let content = std::fs::read_to_string(path).unwrap();
        assert!(content.contains("Test CVE"));
        assert!(content.contains("test-cve"));
        assert!(content.contains("HIGH"));
    }
}
